### ISSUE TITLE
Can't stop keylogger once started

### ISSUE THREAD

**Issue by byt3bl33d3r** [byt3bl33d3r/gcat#1]
This is due to the nature of threads in Python.. Unfortunately we can't use the ```multiprocessing``` library because it completely breaks the implant when compiling it using pyinstaller... going to have to come up with a hacky way of doing it

**Comment by famous01** [comment]
love to know more about it..................

**Comment by acaetano** [comment]
Have you tried `"threading"` library (https://docs.python.org/2/library/threading.html)? It is compatible with `"multiprocessing"`, but maybe pyinstaller won't complain about it.

**Comment by byt3bl33d3r** [comment]
@acaetano the ```threading``` library doesn't allow you to stop the threads you create, that's why I used ```multiprocessing```, the problem is that when the script is compiled via pyinstaller or py2exe stopping the keylogger thread with using the ```multiprocessing``` API makes the implant go nutz

**Comment by peasead** [comment]
I compiled this using pyinstaller and the start and stop commands _appear_ to work (both in the output at the command line and in the Gmail account).

That said, where do the keylogging files get stored...or is the file not returned until the keylogger stops and it isn't actually stopping?
