### ISSUE TITLE
Keylogger dosen't work!

### ISSUE THREAD

**Issue by its0x08** [byt3bl33d3r/gcat#19]
I also need the keylogger function to work :100: %

**Comment by byt3bl33d3r** [comment]
Can you describe in a little more detail how it doesn't work? Need the OS, architecture, commands you ran etc...

**Comment by its0x08** [comment]
I've tried this tool on some windows xp and windows 7 but the logger dosen't work ..

**Comment by byt3bl33d3r** [comment]
... ok, i'm still going to need more information, how did you run implant.py? the commands you ran using Gcat? need the OS architectures etc..

**Comment by its0x08** [comment]
Windows-XP-5.1.2600-SP3-x86
this was the last one .. 
I just open win CMD and run the implant.py file ..
python gcat.py -id 9d861ed4-4225-5f7e-bd62-d0dc61224b24 -start-keylogger 
after that I do ..
python gcat.py -id 9d861ed4-4225-5f7e-bd62-d0dc61224b24 -stop-keylogger 
and I never see any log file from the keylogger !

**Comment by byt3bl33d3r** [comment]
Did you follow the instructions in the Readme? did you edit the user and password values in the scripts? did you enable IMAP in the Gmail account ?

**Comment by its0x08** [comment]
yea -_- everything eles is workin .. its just the keylogger ..

**Comment by byt3bl33d3r** [comment]
you did compile implant.py correct?

**Comment by its0x08** [comment]
no I tested it uncompiled..
do I have to compile it for the keylogger to work ? :3

**Comment by byt3bl33d3r** [comment]
yes
