### ISSUE TITLE
imaplib.error: [ALERT] Please log in via your web browser

### ISSUE THREAD

**Issue by FreelancePentester** [byt3bl33d3r/gcat#2]
Traceback (most recent call last):
  File "gcat.py", line 196, in <module>
    gcat = Gcat()
  File "gcat.py", line 56, in __init__
    self.c.login(gmail_user, gmail_pwd)
  File "/usr/lib/python2.7/imaplib.py", line 507, in login
    raise self.error(dat[-1])
imaplib.error: [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)

**Comment by byt3bl33d3r** [comment]
@FreelancePentester you have the disable "Allow less secure apps" under the security settings of the account (Please read the readme)

**Comment by FreelancePentester** [comment]
thanks you! But it is not work for me...

**Comment by byt3bl33d3r** [comment]
@FreelancePentester can you please explain whats not working for you?

**Comment by FreelancePentester** [comment]
sorry for that. I need to install some library on implant.py . :dancer:

**Comment by byt3bl33d3r** [comment]
sounds like a plan!
