### ISSUE TITLE
Error when running gcat.py

### ISSUE THREAD

**Issue by rcslaney** [byt3bl33d3r/gcat#5]
Error:
imaplib.error: Lookup failed x76mb603055274wlx

Could you help? I seem to be getting error after error when trying to compile this into an .exe file, and this error persists when trying to run gcat.* whether from the compiled standalone .exe or directly on the .py file

**Comment by byt3bl33d3r** [comment]
@rcslaney I'm going to need a lot more information... Can you please post the full error traceback, the commands you ran, and the OS you're running implant.py and gcat.py on? 

Thanks

**Comment by rcslaney** [comment]
Sorry yeah of course, I'm running on Windows 8.1 64 bit with Python 2.7.10, I'm running both implant.py and gcat.py on the same machine (for testing purposes), all that's been run is implant.py (running in a separate command window) and then "python gcat.py -list".


Here's the full error trace back:
E:\Program Files\Python\27-32\Scripts>..\python.exe \gcat-master\gcat.py -list
Traceback (most recent call last):
  File "\gcat-master\gcat.py", line 196, in <module>
    gcat = Gcat()
  File "\gcat-master\gcat.py", line 56, in __init__
    self.c.login(gmail_user, gmail_pwd)
  File "E:\Program Files\Python\27-32\lib\imaplib.py", line 520, in login
    raise self.error(dat[-1])
imaplib.error: Lookup failed x76mb603055274wlx

**Comment by byt3bl33d3r** [comment]
@rcslaney you sure you're username and password are correct? and you enabled "Allow less secure apps" in the account security settings?

**Comment by rcslaney** [comment]
Yeah I've enabled the less secure apps in settings and copying and pasting the credentials directly into google login works so they must be correct, would it not cause an error in implant.py too if they were wrong?

**Comment by byt3bl33d3r** [comment]
@rcslaney no because all errors are suppressed, this way the backdoor always keeps running..
This seems to be an auth problem since the error is caused when logging in, are you on a network that blocks imap/smtp traffic by any chance?
