### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by peasead** [byt3bl33d3r/gcat#6]
I am not getting any results from the ```-screenshot``` command.

I see a jobid at the command line and I see it in Gmail (```{'CMD': 'screenshot', 'ARG': ''}```), but I'm not seeing the screenshot in Gmail or in /data

Was there a library that was needed prior to compiling with pyinstaller? I install pyscreenshot.

I've tried this just running python and compiled.

**Comment by akashsinghsonofgita** [comment]
It requires PIL for the Screenshot feature. Do you have it installed on your system ??

**Comment by peasead** [comment]
Yeah, I installed PIL.

Let me check to make sure it worked properly.
